<?= $this->doctype();?>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle($this->translate('Application Name') . ' | ' . $this->translate('Application Slug'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>           
        <!-- Le styles -->                               
        <?= $this->headStyle() ?>
        <?=
                $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/assets/img/favicon.ico')))
                ->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath('/assets/img/favicon.ico')));
        ?>           
        <!-- Scripts -->        
        <?= $this->headScript() ?>        
    </head>    
    <body class="flat-blue" data-js-libs='<?= $this->requireJsLibs ? json_encode($this->requireJsLibs) : '{}' ?>' data-js-files='<?= $this->requireJsFiles ? json_encode($this->requireJsFiles) : '{}' ?>' style="<?= (!$this->userModel->loggedIn()) ? 'margin-top: 0px;' : '' ?>">        
        <div class="app app-default">                  
            <?php if ($this->forceNotLoggedInLayout) { ?>
                <?= $this->render("layout/not-logged-in.phtml"); ?>
            <?php } elseif ($this->userModel->loggedIn() && $this->userModel->getUserCompany() && !$this->forceSimpleLayout) { ?>            
                <?= $this->render("layout/logged.phtml"); ?>
            <?php } elseif (($this->defaultCompany && $this->defaultCompany->getPeopleDomain()[0]->getDomainType() === 'cfp' && $this->userModel->loggedIn()) || $this->forceSimpleLayout) { ?>                        
                <?= $this->render("layout/logged-simple.phtml"); ?>
            <?php } else { ?>
                <?= $this->render("layout/not-logged-in.phtml"); ?>
            <?php } ?>
        </div>
        <?= $this->inlineScript() ?>                       
    </body>
</html>                                