<aside class="app-sidebar" id="sidebar">
    <div class="sidebar-header">
        <a class="sidebar-brand" href="<?= ($this->defaultCompany && $this->userModel->getUserCompany() && $this->userModel->getUserCompany()->getId() === $this->defaultCompany->getId()) ? '/home/dashboard' : '/home/dashboard' ?>">
            <img alt="<?= $this->translate('Application Name') ?>" src="<?= $this->defaultCompany ? ( $this->defaultCompany->getAlternativeImage() ? $this->defaultCompany->getAlternativeImage()->getUrl() : ($this->defaultCompany->getImage() ? $this->defaultCompany->getImage()->getUrl() : $this->default_company_logo) ) : $this->default_company_logo ?>">
        </a>
        <button type="button" class="sidebar-toggle">
            <i class="fa fa-times"></i>
        </button>
    </div>        
    <div class="sidebar-menu">        
        <ul class="sidebar-nav">
            <?php if ($this->defaultCompany && $this->userModel->getUserCompany() && $this->userModel->getUserCompany()->getId() === $this->defaultCompany->getId()) { ?>
                <?php foreach ($this->_menuModel->getPagesFromPeople(true) AS $menu) { ?>
                    <li class="<?= ($menu['pages']) ? 'dropdown' : '' ?> <?= $this->module_name == strtolower($menu['label']) ? 'active' : '' ?>">
                        <a href="<?= $menu['uri'] ?>" class="<?= ($menu['pages']) ? 'dropdown-toggle' : '' ?>" <?= ($menu['pages']) ? 'data-toggle="dropdown"' : '' ?>>
                            <div class="icon">
                                <i class="<?= $menu['icon_class'] ?>" aria-hidden="true"></i>
                            </div>
                            <div id="menu-<?= $menu['id'] ?>" class="title"><?= $menu['label'] ?></div>
                        </a>
                        <?php if ($menu['pages']) { ?>
                            <div class="dropdown-menu">
                                <ul>                            
                                    <li class="section"><i class="<?= $menu['icon_class'] ?>" aria-hidden="true"></i><?= $menu['label'] ?></li>
                                    <?php foreach ($menu['pages'] AS $submenu) { ?>
                                        <li><a href="<?= $submenu['uri'] ?>"><?= $submenu['label'] ?></a></li>                                            
                                    <?php } ?>
                                </ul>
                            </div>                    
                        <?php } ?>
                    </li>
                <?php } ?>
            <?php } else { ?>
                <?php foreach ($this->_menuModel->getPagesFromPeople(false) AS $menu) { ?>
                    <li class="<?= ($menu['pages']) ? 'dropdown' : '' ?> <?= $this->module_name == strtolower($menu['label']) ? 'active' : '' ?>">
                        <a href="<?= $menu['uri'] ?>" class="<?= ($menu['pages']) ? 'dropdown-toggle' : '' ?>" <?= ($menu['pages']) ? 'data-toggle="dropdown"' : '' ?>>
                            <div class="icon">
                                <i class="<?= $menu['icon_class'] ?>" aria-hidden="true"></i>
                            </div>
                            <div id="menu-<?= $menu['id'] ?>" class="title"><?= $menu['label'] ?></div>
                        </a>
                        <?php if ($menu['pages']) { ?>
                            <div class="dropdown-menu">
                                <ul>                            
                                    <li class="section"><i class="<?= $menu['icon_class'] ?>" aria-hidden="true"></i><?= $menu['label'] ?></li>
                                    <?php foreach ($menu['pages'] AS $submenu) { ?>
                                        <li><a href="<?= $submenu['uri'] ?>"><?= $submenu['label'] ?></a></li>                                            
                                    <?php } ?>
                                </ul>
                            </div>                    
                        <?php } ?>
                    </li>
                <?php } ?>
            <?php } ?>
        </ul>
    </div>
    <div class="sidebar-footer">
        <ul class="menu">
            <li class="">
                <a href="/" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <i class="fa fa-cogs" aria-hidden="true"></i>
                </a>
            </li>
            <li><a href="#"><span class="flag-icon flag-icon-th flag-icon-squared"></span></a></li>
        </ul>
    </div>
</aside>

<?= $this->render("layout/logged-simple.phtml"); ?>