<div class="app-container app-logged-in app-logged-simple">
    <nav class="navbar navbar-default" id="navbar">
        <div class="container-fluid">
            <div class="navbar-collapse collapse in">
                <ul class="nav navbar-nav navbar-mobile">
                    <li>
                        <button type="button" class="sidebar-toggle">
                            <i class="fa fa-bars"></i>
                        </button>
                    </li>
                    <li class="logo">
                        <a class="navbar-brand" href="/<?= $this->module_name ?>">
                            <img height="90%" alt="<?= $this->translate('Application Name') ?>" src="<?= $this->defaultCompany && $this->defaultCompany->getImage() ? $this->defaultCompany->getImage()->getUrl() : $this->default_company_logo ?>">
                        </a>
                    </li>
                    <li>
                        <button type="button" class="navbar-toggle">                                                                
                            <img class="profile-img" src="<?= $this->userModel->getLoggedUser()->getPeople()->getImage() ? $this->userModel->getLoggedUser()->getPeople()->getImage()->getUrl() : $this->default_user_image_profile ?>">
                        </button>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-left">
                    <li class="company-profile">           
                        <a href="/<?= $this->module_name ?>">
                            <img class="company-img" src="<?= $this->defaultCompany && $this->defaultCompany->getImage() ? $this->defaultCompany->getImage()->getUrl() : $this->default_company_logo ?>">                                                
                        </a>
                    </li>                    
                </ul>
                <ul class="nav navbar-nav navbar-right">

                    <li class="dropdown notification">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <div class="icon"><i class="fa fa-shopping-basket" aria-hidden="true"></i></div>
                            <div class="title">New Orders</div>
                            <div class="count">0</div>
                        </a>
                        <div class="dropdown-menu">
                            <ul>
                                <li class="dropdown-header">Ordering</li>
                                <li class="dropdown-empty">No New Ordered</li>
                                <li class="dropdown-footer">
                                    <a href="#">View All <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="dropdown notification warning">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <div class="icon"><i class="fa fa-comments" aria-hidden="true"></i></div>
                            <div class="title">Unread Messages</div>
                            <div class="count">99</div>
                        </a>
                        <div class="dropdown-menu">
                            <ul>
                                <li class="dropdown-header">Message</li>
                                <li>
                                    <a href="#">
                                        <span class="badge badge-warning pull-right">10</span>
                                        <div class="message">
                                            <img class="profile" src="https://placehold.it/100x100">
                                            <div class="content">
                                                <div class="title">"Payment Confirmation.."</div>
                                                <div class="description">Alan Anderson</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="badge badge-warning pull-right">5</span>
                                        <div class="message">
                                            <img class="profile" src="https://placehold.it/100x100">
                                            <div class="content">
                                                <div class="title">"Hello World"</div>
                                                <div class="description">Marco  Harmon</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="badge badge-warning pull-right">2</span>
                                        <div class="message">
                                            <img class="profile" src="https://placehold.it/100x100">
                                            <div class="content">
                                                <div class="title">"Order Confirmation.."</div>
                                                <div class="description">Brenda Lawson</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li class="dropdown-footer">
                                    <a href="#">View All <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="dropdown notification danger">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <div class="icon"><i class="fa fa-bell" aria-hidden="true"></i></div>
                            <div class="title">System Notifications</div>
                            <div class="count">10</div>
                        </a>
                        <div class="dropdown-menu">
                            <ul>
                                <li class="dropdown-header">Notification</li>
                                <li>
                                    <a href="#">
                                        <span class="badge badge-danger pull-right">8</span>
                                        <div class="message">
                                            <div class="content">
                                                <div class="title">New Order</div>
                                                <div class="description">$400 total</div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="badge badge-danger pull-right">14</span>
                                        Inbox
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="badge badge-danger pull-right">5</span>
                                        Issues Report
                                    </a>
                                </li>
                                <li class="dropdown-footer">
                                    <a href="#">View All <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="dropdown profile">
                        <a href="<?= $this->basePath('/' . $this->module_name . '/profile') ?>" class="dropdown-toggle">
                            <img class="profile-img" src="<?= $this->userModel->getLoggedUser()->getPeople()->getImage() ? $this->userModel->getLoggedUser()->getPeople()->getImage()->getUrl() : $this->default_user_image_profile ?>">
                            <div class="title"><?= $this->translate('Profile') ?></div>
                        </a>
                        <div class="dropdown-menu">
                            <div class="profile-info">                                                                                                
                                <h4 class="username"><?= $this->userModel->getLoggedUser()->getPeople()->getName(); ?></h4>
                            </div>
                            <ul class="action">
                                <li>
                                    <a href="<?= $this->basePath('/' . $this->module_name . '/profile') ?>">
                                        <?= $this->translate('Profile') ?>
                                    </a>
                                </li>
                                <li>
                                    <a href="<?= $this->basePath('/' . $this->module_name . '/contact-request') ?>">
                                        <span class="badge badge-danger pull-right">5</span>
                                        <?= $this->translate('My Inbox') ?>
                                    </a>
                                </li>
                                <?php if ($this->defaultCompany && $this->userModel->getUserCompany()) { ?>
                                    <li>
                                        <a href="<?= $this->basePath('/company') ?>">                                                        
                                            <?= $this->translate('Company') ?>
                                        </a>
                                    </li>
                                <?php } ?>               
                                <li>
                                    <a href="<?= $this->basePath('/' . (in_array(strtolower($this->module_name), array('carrier','client','company','provider','salesman'))?strtolower($this->module_name):'user') . '/logout') ?>">                                                        
                                        <?= $this->translate('Logout') ?>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>                                                          
    <div class="show-messages row">
        <!-- This div (class .show-messages) receives all system alerts  -->
    </div>
    <?= $this->content; ?>      
    <footer class="app-footer"> 
        <!--<img src="http://www.hinode.com.br/wp-content/uploads/2017/05/SITE_Campanha-01.png" style="width: 100%;right: 0;margin-bottom: 20px;">-->
        <div class="row">
            <div class="col-xs-12">
                <div class="footer-copyright">
                    Copyright © <?= date('Y') ?> <?= $this->translate('Application Name') ?>
                </div>
            </div>
        </div>
    </footer>         
</div>